name: Continuous Integration
on:
  pull_request:
    branches:
      - master
jobs:
  main:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node-version: [14.x,  16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Lint Commit Message
        run: |
          yarn add -D @commitlint/config-conventional
          echo $(git log -1 --pretty=format:"%s") | yarn commitlint

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install


      - name: Build
        run: yarn build

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn test
