name: Build package
on:
  push:
    branches:
      - master
jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Release
        run: yarn publish --new-version $(npx -c 'echo "$npm_package_version"')

      - name: Tag release
        run: |
          git tag Chillibean-v$(npx -c 'echo "$npm_package_version"')
          git push --tags --no-verify    
